/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LoteDeCarros;

import DataManager.*;
import DataManager.Pool.*;
import DataIO.*;
import java.util.Scanner;

public class App {
    

    public static Scanner lectura = new Scanner(System.in);

    public static void preloadDemostration() {
        // Demostracion altas
        try {

            Brand marca = new Brand();
            marca.setBrandName("BMW");
            BrandPool.get().registerComponent(marca);

            Brand marca2 = new Brand();
            marca2.setBrandName("Ferrari");
            BrandPool.get().registerComponent(marca2);

            Model modeloSport = new Model(marca);
            modeloSport.setModelName("300-I");
            modeloSport.setDoorCount(2);
            modeloSport.setFuelCapacity(30.5);
            modeloSport.setHasSunroof(true);
            modeloSport.setModelYear(2018);
            modeloSport.setSeatCount(2);
            ModelPool.get().registerComponent(modeloSport);

            Model modeloCasual = new Model(marca2);
            modeloCasual.setModelName("X5");
            modeloCasual.setDoorCount(4);
            modeloCasual.setFuelCapacity(25.5);
            modeloCasual.setHasSunroof(true);
            modeloCasual.setModelYear(2012);
            modeloCasual.setSeatCount(5);
            ModelPool.get().registerComponent(modeloCasual);

            Vehicle carro1 = new Vehicle(modeloCasual);
            carro1.setColor("Rojo Rayo McQueen");
            carro1.setMileage(432.0);
            carro1.setVIN("NUMERO VIN");
            carro1.setlicensePlate("2FAST4U");
            VehiclePool.get().registerComponent(carro1);
            Vehicle carro2 = new Vehicle(modeloCasual);
            carro2.setColor("Azul");
            carro2.setMileage(1000.0);
            carro2.setVIN("NUMERO VIN2");
            carro2.setlicensePlate("SOCCERMOM<3");
            VehiclePool.get().registerComponent(carro2);
        } catch (ComponentNotBoundToPool ex) {
            System.out.println("Error: " + ex.getMessage());
        }

    }

    public static ICapture selectTargetGroup() {
        String prompt = new String();
        final int kBrands = 1;
        final int kModels = 2;
        final int kVehicles = 3;
        final int kCancel = 4;
        prompt += "Seleccione que elemento desea consultar o alterar:\n";
        prompt += "1) Marcas\n";
        prompt += "2) Modelos\n";
        prompt += "3) Vehiculos\n";
        prompt += "4) Cancelar\n\n";
        prompt += "Input: ";
        var cScanner = new ConstrainedScanner(prompt, 1, 4);
        for (;;) {
            switch (cScanner.getValue()) {
                case kBrands:
                    return new BrandCapture();
                case kModels:
                    return new ModelCapture();
                case kVehicles:
                    return new VehicleCapture();
                case kCancel:
                    System.exit(0);
            }
        }
    }

    public static void selectOperation(ICapture targetGroup) {
        String prompt = new String();
        final int kCreate = 1;
        final int kRead = 2;
        final int kUpdate = 3;
        final int kDelete = 4;
        final int kCancel = 5;
        prompt += "Selecciona la operacion que deseas realizar:\n";
        prompt += "1) Crear\n";
        prompt += "2) Leer\n";
        prompt += "3) Modificar\n";
        prompt += "4) Borrar\n";
        prompt += "5) Cancelar\n\n";
        prompt += "Input: ";
        var cScanner = new ConstrainedScanner(prompt, 1, 4);
        switch (cScanner.getValue()) {
            case kCreate:
                targetGroup.onCreate();
                return;
            case kRead:
                targetGroup.onBrowse(false);
                return;
            case kUpdate:
                targetGroup.onUpdate();
                return;
            case kDelete:
                targetGroup.onDelete();
                return;
            case kCancel:
                return;
            
        }
    }

    public static void main(String[] args) {
        preloadDemostration();
        for (;;) {
            ICapture captureObj = selectTargetGroup();
            selectOperation(captureObj);
        }

    }
}
